### ISSUE TITLE
图片管理工具

### ISSUE THREAD

**Issue by gsgysm** [TureeZhang/CSL-CN#1]
需要图片管理工具

**Comment by gsgysm** [comment]
文章管理工具（可跳转到之前的任意一级）

**Comment by TureeZhang** [comment]
@gsgysm 需要完善此功能的更多说明。

请大致描述功能内容，或者能够以图片方式提供其他已经实现此功能的软件（或网站）示例最佳。

**Comment by TureeZhang** [comment]
图片管理工具目前暂时完成了上传工具。

使用示例：

![demo](https://user-images.githubusercontent.com/30072809/73354046-b88af780-42cf-11ea-9255-1ec8506eb08a.gif)

**Comment by TureeZhang** [comment]
@gsgysm 

已发布至正式环境 www.cities-skylines.cn ，若上传工具使用正常，则可**关闭此 issue**。

**Comment by TureeZhang** [comment]
@gsgysm 文章管理工具（可跳转到之前的任意一级）gsgysm 文章管理工具（可跳转到之前的任意一级），此说明按照议题独立性原则，已被迁移，前往 https://github.com/TureeZhang/CSL-CN/issues/15 追踪最新进展。
