### ISSUE TITLE
DLC界面无法点进去

### ISSUE THREAD

**Issue by XueshengjunX** [TureeZhang/CSL-CN#30]
![image](https://user-images.githubusercontent.com/62059779/76679478-dca25e00-661b-11ea-9788-95fb52c7ce37.png)
如图，右侧的DLC无法点进去。

**Comment by XueshengjunX** [comment]
另外如何新建文档啊（不是子文档的那种）

**Comment by TureeZhang** [comment]
已知悉，会尽快跳转到准确的DLC介绍界面。

创建文档暂时不行，主要我没想好怎么显示自定义创建的新文档，目录放到哪里去呢…

**Comment by TureeZhang** [comment]
**已完成跳转支持。**
