### ISSUE TITLE
好像  。 界面适配有问题欸。

### ISSUE THREAD

**Issue by stdAri** [TureeZhang/CSL-CN#32]
![QQ图片20200401183421](https://user-images.githubusercontent.com/7691836/78127841-7143f300-7447-11ea-9c15-03f22e8def08.png)

这个界面。。。

适配有问题啊。。嗯应该是适配的问题。。

**Comment by TureeZhang** [comment]
已知悉，确实是适配问题哈哈。左侧文档目录为了保证排列样式，外侧设定了最小宽度导致栅格化在自适应时宽度过大了 😂

**Comment by TureeZhang** [comment]
问题已解决，关闭此 issue 。
