### ISSUE TITLE
关于右侧最近编辑和DLC部分大小跳动问题

### ISSUE THREAD

**Issue by CareyTang** [TureeZhang/CSL-CN#38]
右侧的“最近编辑”模块是一直更新跳动的，但是每次跳动后的整个“最近编辑”模块的大小和上次有可能会不一样。这导致每次跳动之后我鼠标停留在下面的DLC部分的指针可能会被迫偏移。
这是因为“最后编辑：XXXXX XX-XX-XX”这个地方由于编辑者名字的长度不同导致有可能会出现两行，这样子就会影响单个编辑框的高度，继而影响总体最近编辑的高度。这样子下面的DLC部分加入原本鼠标已经准备点击某个DLC，就会被这个高度变化导致从准备点击的DLC上移开。

**Comment by TureeZhang** [comment]
@CareyTang 非常感谢反馈！已知悉情况，确实没有考虑到编辑者名字过长的情况。

可能考虑设置一个最大高度做限制，或者适当增加最近编辑框的宽度。已确认问题。

**Comment by TureeZhang** [comment]
已修复问题，关闭此 issue 。
