### ISSUE TITLE
【问题】【已知问题】目前文章提取速度变慢

### ISSUE THREAD

**Issue by XueshengjunX** [TureeZhang/CSL-CN#46]
我就是补个issues
解决的过程放这里吧~

**Comment by TureeZhang** [comment]
还是你会玩。

**Comment by TureeZhang** [comment]
**经观察速度已恢复。目前已优化日志系统，观察 CPU 使用率已显著下降。**

此前的日志功能可能出现代码缺陷，导致 CPU 占用过高。阿里云都专门来电话了提醒占用问题，说是不是有安全漏洞注意防范及时修补漏洞，我告知是自己的程序代码问题，阿里这波操作爱了。

下图显示自修复以来 CPU 占用已回落正常水平：

![image](https://user-images.githubusercontent.com/30072809/86487674-4d1ee780-bd91-11ea-8b7a-2d4756753d3c.png)
