### ISSUE TITLE
左侧导航栏不支持独立滚动

### ISSUE THREAD

**Issue by C6H11OH** [TureeZhang/CSL-CN#48]
页面左侧的导航栏(此问题发布时)是与页面相对固定，与页面一起滚动的。
主要缺陷
1. 需要滚动到页面上方才能完整看到导航栏(图)，可改进为导航栏独立于页面浮动
![image](https://user-images.githubusercontent.com/60157095/85237212-5055c300-b3e2-11ea-842f-ac5a79108828.png)

这属于可改进项

**Comment by TureeZhang** [comment]
**感谢建议~ 将进行改进！** 

>当右侧内容较长时，使用固定的左侧侧边栏确实可以提供更好的体验。

初期考虑是右侧内容较短，左侧固定会带来奇怪的感受。
但目前页面确实已经开始变的比较长了。

**Comment by TureeZhang** [comment]
左侧菜单已固定，并添加折叠展开按钮，匹配了响应式界面，当宽度较小时自动折叠。

关闭此 iisue 。
