### ISSUE TITLE
引擎的目录标题识别逻辑问题

### ISSUE THREAD

**Issue by suiyueou** [TureeZhang/CSL-CN#55]
刚刚使用中发现引擎的目录标题识别逻辑可能有点小问题，
正常来说，代码块里的标签是不应该被识别到的。
![QQ3`6%3BN(CD2IW{% SLK Y](https://user-images.githubusercontent.com/48700331/86556740-bfa4e880-bf86-11ea-81a6-23f2f5de57a1.png)
![H%CALC7ICMOKHAH2 2B LU](https://user-images.githubusercontent.com/48700331/86556744-c16eac00-bf86-11ea-826c-72eceb92292e.png)

ps：目录能识别的标题标签似乎只有 2级和 3级？

**Comment by TureeZhang** [comment]
有一个思路：

目前是抓取所有 ``## ###`` 开头的内容构建标题的，很难识别 ## 到底出现在代码块内还是外。

转换思路：

使用服务端 markdown 转换工具转换文本为 html ，再捕获 html 标签的文本内容即可。

**Comment by TureeZhang** [comment]
问题已修复，关闭此 issue 。
