### ISSUE TITLE
需要表格表头跟随移动功能

### ISSUE THREAD

**Issue by gsgysm** [TureeZhang/CSL-CN#56]
此功能能够使得浏览者在浏览长表格时能够随时对相应表头，不至于重复滑到表格顶端对应

**Comment by TureeZhang** [comment]
已确认技术方案：https://c.runoob.com/codedemo/4128

题外话：后续会开发**表格编辑器**创建复杂表格，但技术难度很大，仍在储备当中。目前表格会暂时进行简单优化，达到友好可用的程度。

**Comment by TureeZhang** [comment]
功能已增加，关闭此 issue 。
