### ISSUE TITLE
引擎的目录标题标签跳转识别问题

### ISSUE THREAD

**Issue by suiyueou** [TureeZhang/CSL-CN#57]
我在编辑和阅读过程中发现右侧目录里有些标题标签可能会出现无法跳转的情况！

比如，下方文章里的这三个标题标签就出现了无法跳转的情况：

图中文章地址：http://www.cities-skylines.cn/wiki-passage/contribute

![6R2A58_(%KQHXE OPOPREWB](https://user-images.githubusercontent.com/48700331/86600742-0ddfd900-bfd3-11ea-882c-3aff0edba12d.png)

**Comment by TureeZhang** [comment]
问题已修复，关闭此 issue 。

原因是文档内的标题 id 包含英文字母时会强制小写，而滚动侦测组件没有将跳转的目标 id 强制小写。只有一一对应时，跳转才能生效。
