### ISSUE TITLE
关于添加Mod百科

### ISSUE THREAD

**Issue by XueshengjunX** [TureeZhang/CSL-CN#69]
现在似乎已经没有太多可以编辑添加的条目了，希望能增加Mod百科，让百科更有活力和实用性（可参考www.mcmod.cn）

**Comment by TureeZhang** [comment]
已确认，计划会在 1.1 版本落实此版块。感谢！ @xueshengjun233

**Comment by TureeZhang** [comment]
调整在 1.0 落地，因为 1.0 支持文章及分类管理器，此功能可一同发布支持。

**Comment by TureeZhang** [comment]
已开发结束，并已发布。
