### ISSUE TITLE
MOD推荐列表页 表头与表格对齐出现问题

### ISSUE THREAD

**Issue by MrTanXin** [TureeZhang/CSL-CN#78]
## 正确情况
  - 表头与表格对齐
## 当前情况
  - 任意缩放、浏览器全屏运行的情况下，页面基本显示正常（也是略微偏右但是看的不明显）
  - 当非全屏预览或打开F12，表头向右偏移的问题加重
## 附错误的情况下图片一张
![QQ截图20201017213207](https://user-images.githubusercontent.com/26486470/96338388-41e19480-10c0-11eb-927e-0dd16cfa5b08.png)

**Comment by TureeZhang** [comment]
**非常感谢反馈，此问题已修复并上线正式环境。** @MrTanXin 

另外由于浏览器缓存的存在，查看最新的界面可能需要 Ctr+F5 强制刷新之后才能获取到最新的前端文件。

![demo](https://user-images.githubusercontent.com/30072809/96359841-d6440980-1149-11eb-9402-3a409499be9f.png)
![demo](https://user-images.githubusercontent.com/30072809/96359853-fa074f80-1149-11eb-82fa-fa7cfbc5dfc7.png)
