### ISSUE TITLE
关于内容页最后编辑时间格式优化

### ISSUE THREAD

**Issue by TryBin03** [TureeZhang/CSL-CN#88]
第一眼看还以为是没有年份，仔细观看后发现时间格式和我们常用的时间格式不同，建议改成：yyyy-MM-dd HH:mm:ss 这种格式便于理解观看。建议还望采纳，谢谢(^0^)

**Comment by TureeZhang** [comment]
采纳~ 非常感谢！竟然没有收到 issue 通知邮件，现在才看到，已排进开发计划~
